### ISSUE TITLE
VL Performance Tab: Status of VL Scale Up Visual

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#12]
Say percent but displaying absolute numbers, which don't match the data on the  data completeness tab. 

- [ ] Should show percentage
- [ ] Labels should be color coded to series legend

**Comment by Yabayabadoo** [comment]
![image](https://user-images.githubusercontent.com/34660366/48807389-61f95500-eceb-11e8-966d-06ca86170f3f.png)

**Comment by anu87** [comment]
I have a lot of difficulties with this visual. Every time I use any slicers the formatting disappears. The reason I coloured both labels the same, is that way the colour doesn't disappear when slicers are used.

**Comment by Yabayabadoo** [comment]
Then the label colors should be completely different from any of the series colours, white with black text might work. so would no colouring and just black text

**Comment by anu87** [comment]
converted to regular graph from pivotchart - works fine now
