### ISSUE TITLE
VL Performance Tab: Pregnant women VL Cascade Chart

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#13]
![image](https://user-images.githubusercontent.com/34660366/48807767-915c9180-ecec-11e8-9e5c-f7fa243b7f50.png)

The data feeding this chart is all wrong. Eligible pregnant women is point to a TX_NEW chart for a reference that doesn't exist. 

VL documented pregnant women is summing across Test indication disaggs with no relation to pregnant women. Please check.

**Comment by anu87** [comment]
Hey! So, I replacing all the formulae with getPivotdata statements. There's a lot of missing data that is throwing of the existing formula - because when I checked with just Botswana it was pulling in the right data

**Comment by anu87** [comment]
Hi Yaa, the version I have uses the formula we discussed: VL coverage, Pregnant = TX_PVLS, D (PREG ROUTINE + TARGETED + UNDOCUMENTED) / PMTCT_ART (ALREADY ON ART), FY18APR

I am not sure, how you're getting this error. What OU was this for?

**Comment by anu87** [comment]
So, I see the error now. Some countries have no data in PMTCT_ART and then the pivot table just becomes a TX_NEW pivot. I found this error in at least Central Asia Region.

**Comment by Yabayabadoo** [comment]
Hi Anu, That's correct, I found it in Central America as well. Re: Getpivots, can we wrap them in IFERRORs please? !Ref# doesn't give a very clean look.

**Comment by anu87** [comment]
Yeah, i'm changing that. Do you have a time to talk? I was thinking of replacing the psnu_im data with MSD psnu_im whenever it comes out today

**Comment by Yabayabadoo** [comment]
Yes, I am free now.
