### ISSUE TITLE
VL Performance Dashboard: Inconsistent data displayed( TX_RET)

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#14]
![image](https://user-images.githubusercontent.com/34660366/48808031-72123400-eced-11e8-9a9b-ab82cd2c31de.png)

Data Completeness Review tab for cAM

![image](https://user-images.githubusercontent.com/34660366/48808077-a0900f00-eced-11e8-9185-e18036807ef3.png)

VL performance tab for same

**Comment by anu87** [comment]
May have been some issue with the reference cell changing - it appears fine in the current version
![image](https://user-images.githubusercontent.com/17214140/48869215-620c5a00-edaa-11e8-8958-37171e1c4e5d.png)
