### ISSUE TITLE
Data Completeness Review Tab (updated version): PMTCT_ART Chart

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#18]
![image](https://user-images.githubusercontent.com/34660366/48851993-6b7dce00-ed7a-11e8-99bf-83f2376a5619.png)

Hi Anu, I think the label for the disaggregate is pointing to the wrong cell. The name of the PMTCT ART disaggregate is 'NewExistingArt/Sex/HIVStatus'

**Comment by anu87** [comment]
Yes, but Life-long ART existing & new are other-disaggregates under 'NewExistingArt/Sex/HIVStatus'. Isn't it  suppose to also show disaggregates of 'NewExistingArt/Sex/HIVStatus' stacked?

**Comment by Yabayabadoo** [comment]
That's correct, but the axis label says 'disaggregate' instead of 'NewExistingArt/Sex/HIVStatus'

**Comment by anu87** [comment]
done
