### ISSUE TITLE
Illogical site counts

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#2]
Total Country site counts are illogical. Check calculation or share code used to generate counts please.

**Comment by anu87** [comment]
Found the error - ran simple count , instead of distinct count. Code now:

`site_im %>% group_by(PSNU, PSNUuid) %>% mutate(site_count=n_distinct(Facility))`

**Comment by Yabayabadoo** [comment]
Awesome, thanks Anu. Particularly for items that issues that have required updates to the backend dataset can you share an updated tool before you leave today? I shall check in the evening when I land.
