### ISSUE TITLE
Systems Quality Tab: Ranking formula for table

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#21]
![image](https://user-images.githubusercontent.com/34660366/48857892-fd400800-ed87-11e8-9942-19fec4c0985e.png)
 The ranking for the bottom 3 seems off, last item should be first among the 3 and a tie break for the rows with zeros across, no?

**Comment by anu87** [comment]
I know about this issue - the code needs to tweaked around to fix this issue - but I didn't have time to this. I am not sure why this happened to I need to explore the code and try some new R functions. This will take some time and don't have time to address this until later next week.

**Comment by anu87** [comment]
Fixed - now the table doesn't show facilities that have not reported tx_curr, they are also not part of the ranking system
