### ISSUE TITLE
VL Performance Tab: Formatting, Focus Population Charts

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#22]
![image](https://user-images.githubusercontent.com/34660366/48859988-9a516f80-ed8d-11e8-8549-17fb00b28b3f.png)

Per Catherine's comment, we can afford to scale the page to 75% And increase the font size on the data labels to 10.5. Please see top right hand corner of screen shot for dimensions used.

**Comment by anu87** [comment]
done
