### ISSUE TITLE
VL Performance Tab: TX_RET Chart Formatting and Table edits

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#23]
![image](https://user-images.githubusercontent.com/34660366/48860548-3465e780-ed8f-11e8-8ce3-bda26034d1ad.png)

Modified the sizing of retention charts. Table with Retention data, '15+' row should be directly below <15 with other semi-fine age bands grouped together.

**Comment by Yabayabadoo** [comment]
Also the chart title should include Total since we combined the two graphs

**Comment by anu87** [comment]
done
