### ISSUE TITLE
VL performance Tab: Focus Population Charts

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#24]
![image](https://user-images.githubusercontent.com/34660366/48947813-79f5f200-ef00-11e8-895a-80982da7c9ab.png)

VL Coverage rate data point should be above the TX_PVLS, D (like it is now), but suppression rate should be above the TX_PVLS, N bar, right now it looks like you are using the same x-axis reference for data points.

**Comment by anu87** [comment]
done
