### ISSUE TITLE
Systems Quality Tab: Site Rank Table, Formatting Change

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#27]
![image](https://user-images.githubusercontent.com/34660366/48948608-0ef9ea80-ef03-11e8-826d-2842b3bf826d.png)

Can we center the percentages? Also Helen Chun requested conditional formatting to identify sites quickly.

for VL coverage: <75% (poor), 75 to <90 is good, >=90 is great
for VL Suppression: <90 is okay, >90 is good
I'll leave the color choice to you.

**Comment by anu87** [comment]
done
