### ISSUE TITLE
Start Here Tab: Formatting Chages

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#28]
Consistent language changes:

![image](https://user-images.githubusercontent.com/34660366/48948932-47e68f00-ef04-11e8-888c-ab0724d0e2a0.png)
 Added Load to 2.

![image](https://user-images.githubusercontent.com/34660366/48948999-719fb600-ef04-11e8-98e4-ebd645910428.png)

Removed 'nationally, and within' from  paragraph

**Comment by anu87** [comment]
done
