### ISSUE TITLE
VL Performance Tab: OU & PSNU Selected title

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#29]
![image](https://user-images.githubusercontent.com/34660366/48949843-6a2ddc00-ef07-11e8-8d00-9797ca197e50.png)

In the original version of the tool, did we have a page title that told you selected OU and PSNU? Right now it is difficult to know; particularly when the selected OU is towards the bottom of the slicer. Let's put it back up and freeze the pane so it shows with scrolling.

**Comment by anu87** [comment]
done
