### ISSUE TITLE
Inconsistent labeling charts

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#3]
![image](https://user-images.githubusercontent.com/34660366/48800786-c2cb6200-ecd8-11e8-839c-1595363ecced.png)

**Comment by anu87** [comment]
I kept the axis labels just on the right side graphs, thinking it is redundant to have the same axis labels on graphs side by side. So, I did this on purpose - do you want me to change this?

**Comment by Yabayabadoo** [comment]
I also think it is duplicative, but the leads seem to think it was necessary so let's modify please.

**Comment by Yabayabadoo** [comment]
@anu87 while you are making these edits, some of the series names appear off center

![image](https://user-images.githubusercontent.com/34660366/48805374-38d5c600-ece5-11e8-91ac-55e14d598086.png)

**Comment by anu87** [comment]
Sure, I'll do that. I think the leads comment was on the previous version, where only TX_RET graph on left had  a label. I changed that kept all labels on right side. Below is there comment, let me know if you still prefer to add labels on both left & right. I just think it makes the graphs too busy.

•	Y axis labeling is not consistent. All graphs on the left have a label but only the TX_RET graph on the RIGHT has a label. Either remove to match all other right sides graphs or put labels for Y axis on all other graphs as well. JD: second this

**Comment by Yabayabadoo** [comment]
Got it, let's go with what you've done.
