### ISSUE TITLE
Systems Quality Tab: Summary Table

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#30]
![image](https://user-images.githubusercontent.com/34660366/49088732-e84ff280-f227-11e8-83ec-72f2872a4777.png)

![image](https://user-images.githubusercontent.com/34660366/49088751-f69e0e80-f227-11e8-8aac-51e1d1168c6f.png)

For sites reporting TX_CURR and PVLS, I see several instances where the count is exactly double of the sites listed in the site rank table. For example a single PSNU (_militaryOU) still shows 2 sites, where there should technically be only 1. Is there an issue with the site count across the indicators?

**Comment by anu87** [comment]
fixed
