### ISSUE TITLE
Systems Quality Tab: Summary Table

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#31]
![image](https://user-images.githubusercontent.com/34660366/49089000-9065bb80-f228-11e8-9faf-9bdffffab3bd.png)
 I thought the site count was mutually inclusive? If  no sites reported in TX_CURR AND TX_PVLS, why is there a count of 4 for 'Sites reporting on TX_CURR and PVLS'?

**Comment by anu87** [comment]
done
