### ISSUE TITLE
VL Performance Tab: Status of VL Monitoring 

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#32]
![image](https://user-images.githubusercontent.com/34660366/49317304-f02ac380-f4c1-11e8-82c7-0af9bb083ea2.png)

**Comment by Yabayabadoo** [comment]
issue here is that ROutine tests are greater than total tests performed. Not consistent with the values on other tabs

**Comment by anu87** [comment]
done
