### ISSUE TITLE
Systems Quality Tab: Lab/POCT Visual

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#33]
![image](https://user-images.githubusercontent.com/34660366/49317388-47309880-f4c2-11e8-9630-5c5a9e8ca049.png)

Move the legend to the bottom so labels aren't blocked.

**Comment by Yabayabadoo** [comment]
Can we also make sure the absolute value has formatted as a number with comma instead of general

**Comment by anu87** [comment]
done
