### ISSUE TITLE
VL Performance Tab: Calculation for Adults 25+ Suppressed 

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#8]
![image](https://user-images.githubusercontent.com/34660366/48806247-b7cbfe00-ece7-11e8-857a-7a29df27be93.png)

It looks like your calculation includes the grand total in pivot table 4. Do you need the row grand totals?

**Comment by anu87** [comment]
Hmm - I will change the formula to getPivotdata and remove grand totals

**Comment by anu87** [comment]
change all to GetPivot data
